//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop_Project_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class get_category
    {
        public int code_category { get; set; }
        public string name { get; set; }
    }
}
