//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop_Project_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class get_goods
    {
        public int article_number { get; set; }
        public string photo { get; set; }
        public string name { get; set; }
        public string descrtiption { get; set; }
        public string category_name { get; set; }
        public string manufacturer_name { get; set; }
        public Nullable<decimal> price { get; set; }
    }
}
