//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop_Project_API.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class good_rate
    {
        public int id { get; set; }
        public int article_number { get; set; }
        public int id_user { get; set; }
        public int rate { get; set; }
        public string feedback { get; set; }

        [JsonIgnore]
        public virtual good good { get; set; }
        [JsonIgnore]
        public virtual user_profile user_profile { get; set; }
    }
}
