//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop_Project_API.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class good_parameter
    {
        public int id_good_parameter { get; set; }
        public int article_number { get; set; }
        public string name { get; set; }
        public string value { get; set; }

        [JsonIgnore]
        public virtual good good { get; set; }
    }
}
