//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop_Project_API.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class order_good
    {
        public int id_order_good { get; set; }
        public int id_order { get; set; }
        public int article_number { get; set; }
        public int count { get; set; }

        [JsonIgnore]
        public virtual good good { get; set; }
        [JsonIgnore]
        public virtual order order { get; set; }
    }
}
